### ISSUE TITLE
Error with pip install on OS X Python 3.4.2

### ISSUE THREAD

**Issue by itsMichaelBates** [mLewisLogic/foursquare#71]
When running `pip install foursquare` inside a virtualenv on OS X 10.11.3 I get the following error:

```
Downloading/unpacking foursquare
  Downloading foursquare-20130707.tar.gz
  Running setup.py (path:/Users/michaelbates/GoogleDrive/Development/storm/storm-python/venv/build/foursquare/setup.py) egg_info for package foursquare
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/michaelbates/GoogleDrive/Development/storm/storm-python/venv/build/foursquare/setup.py", line 7, in <module>
        import foursquare
      File "/Users/michaelbates/GoogleDrive/Development/storm/storm-python/venv/build/foursquare/foursquare/__init__.py", line 690
        except FoursquareException, e:
                                  ^
    SyntaxError: invalid syntax
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/michaelbates/GoogleDrive/Development/storm/storm-python/venv/build/foursquare/setup.py", line 7, in <module>

    import foursquare

  File "/Users/michaelbates/GoogleDrive/Development/storm/storm-python/venv/build/foursquare/foursquare/__init__.py", line 690

    except FoursquareException, e:

                              ^

SyntaxError: invalid syntax

----------------------------------------
Cleaning up...
```

I couldn't find the line that's causing the issue in `__init__.py` in HEAD so it leads me to think I'm installing an old version from PyPI?

**Comment by itsMichaelBates** [comment]
Never mind, it seems 
```
pip install --upgrade pip
```
fixed the issue.
